"""Social Media Automation Rules evaluator — "when a new campaign/shop is
created and matches X, generate a post". Same in-process asyncio poller
pattern as services/automation.py and services/social_publisher.py (this
project has no event bus, so a periodic poll is what "when X happens" means
everywhere else in this codebase too).

Safety, matching the manual composer's own rules exactly:
  * A "group" target is NEVER auto-scheduled — Meta doesn't support
    automated Group posting for anyone (see services/facebook_graph.py) —
    it always lands as manual_required regardless of requires_approval.
  * requires_approval=True (the default) always lands as pending_approval,
    never auto-scheduled, regardless of target_kind.
  * requires_approval=False only auto-schedules when there's a genuinely
    connected, valid-token account for that platform AND the rule has a
    schedule_time configured — otherwise it safely falls back to
    pending_approval rather than silently dropping the post.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone as dt_timezone
from zoneinfo import ZoneInfo

from sqlalchemy import select
from sqlalchemy.orm import selectinload

from ..database import AsyncSessionLocal
from ..models import Campaign, ClientSocialAccount, DistributionPost, Shop, SocialAutomationRule, SocialPostTemplate
from .audit import record_audit
from .distribution import region_for_shop, regions_for_shops
from .social_ai import generate_post_text
from .social_templates import DEFAULT_TEMPLATE, render_template, variables_from_campaign, variables_from_shop
from .tracking import now


def _matches_conditions(entity, conditions: dict) -> bool:
    for field, expected in (conditions or {}).items():
        if getattr(entity, field, None) != expected:
            return False
    return True


def _next_occurrence(schedule_time: str, tz_name: str) -> datetime:
    """Next future UTC datetime for a "HH:MM" time-of-day in the rule's
    timezone — "schedule for next available configured time" from the spec.

    Falls back to plain UTC if the platform has no IANA tzdata available at
    all (zoneinfo needs the `tzdata` package on Windows — see
    requirements.txt) — better to schedule against UTC than to crash the
    whole automation tick over a missing timezone database."""
    try:
        tz = ZoneInfo(tz_name)
    except Exception:  # noqa: BLE001 — tzdata may be entirely absent on this platform
        tz = dt_timezone.utc
    hh, mm = (int(p) for p in schedule_time.split(":"))
    local_now = datetime.now(tz)
    candidate = local_now.replace(hour=hh, minute=mm, second=0, microsecond=0)
    if candidate <= local_now:
        candidate += timedelta(days=1)
    return candidate.astimezone(dt_timezone.utc)


async def _new_campaigns(session, client_id, since: datetime) -> list[Campaign]:
    stmt = select(Campaign).where(Campaign.client_id == client_id, Campaign.created_at > since)
    return list((await session.execute(stmt)).scalars().all())


async def _new_shops(session, client_id, since: datetime) -> list[Shop]:
    stmt = (
        select(Shop)
        .join(Campaign, Shop.campaign_id == Campaign.id)
        .where(Campaign.client_id == client_id, Shop.created_at > since)
        .options(selectinload(Shop.campaign))
    )
    return list((await session.execute(stmt)).scalars().all())


async def _generate_rule_post(session, rule: SocialAutomationRule, *, campaign: Campaign, shop: Shop | None) -> None:
    from ..config import settings

    base_url = settings.public_base_url
    variables = variables_from_shop(shop, campaign, base_url) if shop else variables_from_campaign(campaign, base_url)

    if rule.use_ai:
        message = await generate_post_text(
            platform=rule.destination_type,
            tone=rule.ai_tone,
            language=rule.ai_language,
            variables=variables,
            instructions=f"Automatically generated by the '{rule.name}' automation rule.",
        )
    elif rule.template_id:
        template = await session.get(SocialPostTemplate, rule.template_id)
        body = template.body_template if template else DEFAULT_TEMPLATE
        message = render_template(body, variables)
    else:
        message = render_template(DEFAULT_TEMPLATE, variables)

    region = region_for_shop(shop) if shop else (next(iter(regions_for_shops(list(await campaign.awaitable_attrs.shops))), "Unspecified Region"))
    is_group = rule.target_kind == "group"

    status = "manual_required" if is_group else "pending_approval"
    scheduled_at = None
    if not is_group and not rule.requires_approval and rule.schedule_time:
        account_stmt = select(ClientSocialAccount).where(
            ClientSocialAccount.client_id == rule.client_id,
            ClientSocialAccount.platform == rule.destination_type,
            ClientSocialAccount.status == "connected",
            ClientSocialAccount.access_token_encrypted.is_not(None),
        )
        account = (await session.execute(account_stmt)).scalar_one_or_none()
        if account is not None:
            scheduled_at = _next_occurrence(rule.schedule_time, rule.timezone)
            status = "scheduled"
        # else: no valid connected account — stays pending_approval so the
        # post is never silently lost, matching the manual composer's own
        # "connect an account before scheduling" guard.

    post = DistributionPost(
        campaign_id=campaign.id,
        region=region,
        destination_type=rule.destination_type,
        destination_name=rule.target_ref or f"{rule.destination_type} {rule.target_kind}",
        message=message,
        image_url=None,
        status=status,
        posted_by=f"automation:{rule.name}",
        posted_at=now(),
        source_type="shop" if shop else "campaign",
        source_shop_id=shop.id if shop else None,
        target_kind=rule.target_kind,
        target_ref=rule.target_ref,
        timezone=rule.timezone,
        scheduled_at=scheduled_at,
        requires_manual_posting=is_group,
    )
    session.add(post)
    await session.flush()
    await record_audit(
        session,
        action="social_automation.post_generated",
        actor=f"automation:{rule.name}",
        entity_type="distribution_post",
        entity_id=str(post.id),
        summary=f"Rule '{rule.name}' generated a {rule.destination_type} post for {campaign.name}",
        meta={"rule_id": str(rule.id), "trigger": rule.trigger, "status": status},
    )


async def process_automation_rules() -> int:
    """One scheduler tick. Returns the number of posts generated."""
    generated = 0
    async with AsyncSessionLocal() as session:
        rules = (
            await session.execute(select(SocialAutomationRule).where(SocialAutomationRule.enabled.is_(True)))
        ).scalars().all()

        for rule in rules:
            rule_id = rule.id
            watermark = rule.last_run_at or rule.created_at
            try:
                if rule.trigger == "campaign_created":
                    for campaign in await _new_campaigns(session, rule.client_id, watermark):
                        if _matches_conditions(campaign, rule.conditions):
                            await _generate_rule_post(session, rule, campaign=campaign, shop=None)
                            generated += 1
                elif rule.trigger == "shop_created":
                    for shop in await _new_shops(session, rule.client_id, watermark):
                        if _matches_conditions(shop, rule.conditions):
                            await _generate_rule_post(session, rule, campaign=shop.campaign, shop=shop)
                            generated += 1
                rule.last_run_at = now()
                await session.commit()
            except Exception as exc:  # noqa: BLE001 — one rule's failure must never break the others
                await session.rollback()
                print(f"WARNING: ShopperMatch social automation rule {rule_id} failed: {exc!r}")
    return generated


async def run_social_automation_scheduler() -> None:
    """Runs for the FastAPI process lifetime — background, browser-independent."""
    import asyncio

    from ..config import settings

    while True:
        try:
            await process_automation_rules()
        except asyncio.CancelledError:
            raise
        except Exception as exc:  # noqa: BLE001 - keep the scheduler alive
            print(f"WARNING: ShopperMatch social automation scheduler error: {exc}")
        await asyncio.sleep(settings.automation_poll_seconds)
